server:
  port: 81
  servlet:
    context-path: /social-network

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/social_network"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  using-time: 24
  signer-key: "aGm8QN6YqkOn8lXEy?9Q09Sf8tpOzkuJoiXhO4CLt?007eZ?=BSGNzVbA1eJM702"

cloud:
  name: "dfh3lweic"
  api-key: "276797494958256"
  api-secret: "fvLq2Lg_5YoGp0ZZhCaySmb-2hg"


logging:
  level:
    root: INFO
    com:
      example: DEBUG
    org:
      springframework:
        web:
          socket: DEBUG
        messaging: DEBUG
      hibernate: DEBUG

